#!/usr/bin/bash

# make the ~/.naja through git
cd ~; git clone --bare https://github.com/rhrslxzp/.naja

# make link for nazja.sh to path
# make a ~/localpath
# e.g. $ ln -s /original ~/localpath/link <- do not need su preilege

# ask ftp server
# ask scp server



# ask the directory for najafamily -> create or skip

# to run scripts in .naja for initialization

# how to train naja
